CREATE TABLE IF NOT EXISTS characters (
    characterId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userId INTEGER NOT NULL,
    characterRole TEXT NOT NULL,
    characterName TEXT,
    species TEXT NOT NULL,
    attributes INTEGER ARRAY NOT NULL,
    disciplines INTEGER ARRAY NOT NULL,
    characterValue TEXT,
    equipment TEXT
);