CREATE TABLE IF NOT EXISTS characters (
    character_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    character_name TEXT,
    species TEXT NOT NULL,
    attributes_id INTEGER NOT NULL,
    disciplines_id INTEGER NOT NULL,
    character_value TEXT,
    equipment TEXT
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    user_password TEXT NOT NULL,
    date_joined TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS attributes (
    attributes_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    character_control INTEGER NOT NULL,
    character_daring INTEGER NOT NULL,
    character_fitness INTEGER NOT NULL,
    character_insight INTEGER NOT NULL,
    character_presences INTEGER NOT NULL,
    character_reason INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS disciplines (
    attributes_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    character_command INTEGER NOT NULL,
    character_conn INTEGER NOT NULL,
    character_security INTEGER NOT NULL,
    character_engineering INTEGER NOT NULL,
    character_science INTEGER NOT NULL,
    character_medicine INTEGER NOT NULL
);